# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "Justap" do
pod 'pop', '~> 1.0'
pod 'Firebase', '>= 1.2.0'
pod 'Underscore.m', '~> 0.2'
end

target "JustapTests" do

end

